Update to Go 1.18 and golangci-lint
Fixed issues flagged by golangci-lint:

❯ make
== format
== vet
== lint
WARN [linters context] gosimple is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] staticcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] unused is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
util/slices_test.go:9:6: `blah` is unused (deadcode)
type blah interface {
     ^
util/slices_test.go:12:6: `cat` is unused (deadcode)
type cat struct {
     ^
controller/controller_test.go:1296:5: `expectGetIngresses` is unused (deadcode)
var expectGetIngresses = func(client *fake.FakeClient, ingresses []*v1beta1.Ingress) {
    ^
nginx/nginx_test.go:125:10: Error return value of `lb.Start` is not checked (errcheck)
	lb.Start()
	       ^
nginx/nginx_test.go:139:10: Error return value of `lb.Start` is not checked (errcheck)
	lb.Start()
	       ^
nginx/nginx_test.go:150:10: Error return value of `lb.Start` is not checked (errcheck)
	lb.Start()
	       ^
nginx/nginx_test.go:205:11: Error return value of `file.Read` is not checked (errcheck)
	file.Read(buf)
	        ^
nginx/nginx_test.go:2203:14: Error return value of `metric.Write` is not checked (errcheck)
	metric.Write(&metricVal)
	           ^
nginx/nginx_test.go:182:2: ineffectual assignment to err (ineffassign)
	err = lb.Update([]controller.IngressEntry{{
	^
exit status 1
make: *** [Makefile:56: lint] Error 1